/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author santo
 */
public class TelaRelatorioPGA extends javax.swing.JFrame {

    /**
     * Creates new form TelaRelatórioPGA
     */
    public TelaRelatorioPGA() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH); /* comando para abrir em tela cheia */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        RFOR = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Rcli = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btRelatorioFornecedor = new javax.swing.JButton();
        btRelatorioCliente = new javax.swing.JButton();
        btRelatorioFuncionario = new javax.swing.JButton();
        btRelatorioProduto = new javax.swing.JButton();
        btPrincipalRalatorio = new javax.swing.JButton();
        BtVendas = new javax.swing.JButton();
        btentrada = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btInicial = new javax.swing.JButton();
        btSairRelatorio = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btInicialRalatorioMenu = new javax.swing.JMenuItem();
        btEncerrarSessaoRalatorioMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PGA System - Relatório");

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        RFOR.setBackground(new java.awt.Color(0, 102, 255));
        RFOR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RFOR.setForeground(new java.awt.Color(255, 255, 255));
        RFOR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Antrepo-Container-4-Cargo-Vans-Instagram-Van-Front.128.png"))); // NOI18N
        RFOR.setText("Relatório Fonecedor");
        RFOR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RFORActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Iconshock-Real-Vista-Networking-Guard.128.png"))); // NOI18N
        jButton2.setText("Relatório Funcionário");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Rcli.setBackground(new java.awt.Color(0, 102, 204));
        Rcli.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Rcli.setForeground(new java.awt.Color(255, 255, 255));
        Rcli.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icons-Land-Vista-People-Office-Customer-Male-Light.96.png"))); // NOI18N
        Rcli.setText("Relatório Cliente");
        Rcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RcliActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Prasilarts-Claire-Monitor-01-Computer-Violet-Space.128.png"))); // NOI18N
        jButton4.setText("Relatório Produto");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Relatório Geral de Estoque");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PGA System - Relatório de Estoque");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RFOR, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Rcli, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(445, 445, 445)
                        .addComponent(jLabel2)))
                .addGap(0, 153, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(472, 472, 472)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel2)
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RFOR)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Rcli, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4))
                .addGap(161, 161, 161)
                .addComponent(jLabel3)
                .addGap(14, 14, 14))
        );

        jPanel4.setBackground(new java.awt.Color(0, 153, 255));

        btRelatorioFornecedor.setBackground(new java.awt.Color(255, 255, 255));
        btRelatorioFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        btRelatorioFornecedor.setText("Fornecedor");
        btRelatorioFornecedor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btRelatorioFornecedor.setPreferredSize(new java.awt.Dimension(80, 24));
        btRelatorioFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioFornecedorActionPerformed(evt);
            }
        });

        btRelatorioCliente.setBackground(new java.awt.Color(255, 255, 255));
        btRelatorioCliente.setForeground(new java.awt.Color(0, 0, 0));
        btRelatorioCliente.setText("Cliente");
        btRelatorioCliente.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btRelatorioCliente.setPreferredSize(new java.awt.Dimension(80, 24));
        btRelatorioCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioClienteActionPerformed(evt);
            }
        });

        btRelatorioFuncionario.setBackground(new java.awt.Color(255, 255, 255));
        btRelatorioFuncionario.setForeground(new java.awt.Color(0, 0, 0));
        btRelatorioFuncionario.setText("Funcionário");
        btRelatorioFuncionario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btRelatorioFuncionario.setPreferredSize(new java.awt.Dimension(80, 24));
        btRelatorioFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioFuncionarioActionPerformed(evt);
            }
        });

        btRelatorioProduto.setBackground(new java.awt.Color(255, 255, 255));
        btRelatorioProduto.setForeground(new java.awt.Color(0, 0, 0));
        btRelatorioProduto.setText("Produto");
        btRelatorioProduto.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btRelatorioProduto.setPreferredSize(new java.awt.Dimension(80, 24));
        btRelatorioProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRelatorioProdutoActionPerformed(evt);
            }
        });

        btPrincipalRalatorio.setBackground(new java.awt.Color(255, 255, 255));
        btPrincipalRalatorio.setForeground(new java.awt.Color(0, 0, 0));
        btPrincipalRalatorio.setText("Principal");
        btPrincipalRalatorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btPrincipalRalatorio.setPreferredSize(new java.awt.Dimension(80, 24));
        btPrincipalRalatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPrincipalRalatorioActionPerformed(evt);
            }
        });

        BtVendas.setBackground(new java.awt.Color(255, 255, 255));
        BtVendas.setForeground(new java.awt.Color(0, 0, 0));
        BtVendas.setText("Saída");
        BtVendas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        BtVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVendasActionPerformed(evt);
            }
        });

        btentrada.setBackground(new java.awt.Color(255, 255, 255));
        btentrada.setForeground(new java.awt.Color(0, 0, 0));
        btentrada.setText("Entrada");
        btentrada.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 4, true));
        btentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btentradaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btPrincipalRalatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRelatorioProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRelatorioFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRelatorioCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btRelatorioFornecedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btentrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtVendas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btPrincipalRalatorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRelatorioProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRelatorioFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRelatorioCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btRelatorioFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtVendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btentrada)
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Logo_128x128.png"))); // NOI18N

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        btInicial.setBackground(new java.awt.Color(0, 153, 255));
        btInicial.setForeground(new java.awt.Color(0, 153, 255));
        btInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ionic-Ionicons-Home.16.png"))); // NOI18N
        btInicial.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        btInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicialActionPerformed(evt);
            }
        });

        btSairRelatorio.setBackground(new java.awt.Color(0, 153, 255));
        btSairRelatorio.setForeground(new java.awt.Color(0, 0, 0));
        btSairRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Pictogrammers-Material-Exit-run.16.png"))); // NOI18N
        btSairRelatorio.setText("Sair");
        btSairRelatorio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 153, 255), 4, true));
        btSairRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairRelatorioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btInicial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSairRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInicial, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btSairRelatorio, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(39, 39, 39))))
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenuBar1.setForeground(new java.awt.Color(51, 51, 51));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Ionic-Ionicons-Home.16.png"))); // NOI18N

        btInicialRalatorioMenu.setText("Tela Inicial");
        btInicialRalatorioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInicialRalatorioMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btInicialRalatorioMenu);

        btEncerrarSessaoRalatorioMenu.setText("Encerrar Sessão");
        btEncerrarSessaoRalatorioMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEncerrarSessaoRalatorioMenuActionPerformed(evt);
            }
        });
        jMenu1.add(btEncerrarSessaoRalatorioMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Dario-Arnaez-Genesis-3G-User-Files.16.png"))); // NOI18N
        jMenu2.setText("Cadastro");

        jMenuItem1.setText("Funcionário");
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Fornecedor");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Cliente");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Double-J-Design-Ravenna-3d-Box.16.png"))); // NOI18N
        jMenu3.setText("Estoque");

        jMenuItem4.setText("Cadastrar Produto");
        jMenu3.add(jMenuItem4);

        jMenuItem5.setText("Excluir Produto");
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("Alterar Produto");
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icons-Land-Vista-People-Person-Male-Light.16.png"))); // NOI18N
        jMenu6.setText("Pessoa");

        jMenuItem7.setText("Funcionário");
        jMenu6.add(jMenuItem7);

        jMenuItem8.setText("Cliente");
        jMenu6.add(jMenuItem8);

        jMenuItem9.setText("Fornecedor");
        jMenu6.add(jMenuItem9);

        jMenuBar1.add(jMenu6);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Custom-Icon-Design-Flatastic-9-Custom-reports.16.png"))); // NOI18N
        jMenu4.setText("Consulta");

        jMenuItem10.setText("Consulta Rápida");
        jMenu4.add(jMenuItem10);

        jMenuItem11.setText("Consulta Avançada");
        jMenu4.add(jMenuItem11);

        jMenuItem12.setText("Consulta Cliente");
        jMenu4.add(jMenuItem12);

        jMenuItem13.setText("Consulta Fornecedor");
        jMenu4.add(jMenuItem13);

        jMenuItem14.setText("Consulta Funcionário");
        jMenu4.add(jMenuItem14);

        jMenuBar1.add(jMenu4);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Iconmuseo-Egypt-Cleopatra-09-Contextual-Menu-Items.16.png"))); // NOI18N
        jMenu7.setText("Relatório");

        jMenuItem15.setText("Relatório Cliente");
        jMenu7.add(jMenuItem15);

        jMenuItem16.setText("Relatório Fornecedor");
        jMenu7.add(jMenuItem16);

        jMenuItem17.setText("Relatório Funcionário");
        jMenu7.add(jMenuItem17);

        jMenuItem18.setText("Relatório Produto");
        jMenu7.add(jMenuItem18);

        jMenuBar1.add(jMenu7);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Arturo-Wibawa-Akar-Gear.16.png"))); // NOI18N
        jMenu5.setText("Configurações");

        jMenuItem19.setText("Configurações de Acesso");
        jMenu5.add(jMenuItem19);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("PGA  System");

        jMenuItem20.setText("Desenvolvedores PGA System");
        jMenu8.add(jMenuItem20);

        jMenuItem21.setText("Empresa PGA System");
        jMenu8.add(jMenuItem21);

        jMenuItem22.setText("Dúvidas");
        jMenu8.add(jMenuItem22);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btPrincipalRalatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPrincipalRalatorioActionPerformed
       
        new TelaPrincipalPGA().setVisible(true);dispose();
    }//GEN-LAST:event_btPrincipalRalatorioActionPerformed

    private void btRelatorioClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioClienteActionPerformed
        
        new TelaClientePGA().setVisible(true);dispose();
    }//GEN-LAST:event_btRelatorioClienteActionPerformed

    private void btInicialRalatorioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicialRalatorioMenuActionPerformed
       
        new TelaLoginPGA().setVisible(true);dispose();
    }//GEN-LAST:event_btInicialRalatorioMenuActionPerformed

    private void btEncerrarSessaoRalatorioMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEncerrarSessaoRalatorioMenuActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btEncerrarSessaoRalatorioMenuActionPerformed

    private void btRelatorioProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioProdutoActionPerformed
        
        new TelaProdutoPGA().setVisible(true);dispose();
    }//GEN-LAST:event_btRelatorioProdutoActionPerformed

    private void btRelatorioFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioFuncionarioActionPerformed
        
        new TelaFuncionarioPGA().setVisible(true);dispose();
    }//GEN-LAST:event_btRelatorioFuncionarioActionPerformed

    private void btRelatorioFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRelatorioFornecedorActionPerformed
        
        new TelaFornecedorPGA().setVisible(true);dispose();
    }//GEN-LAST:event_btRelatorioFornecedorActionPerformed

    private void btInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInicialActionPerformed
        
        new TelaLoginPGA().setVisible(true);dispose();
    }//GEN-LAST:event_btInicialActionPerformed

    private void btSairRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairRelatorioActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_btSairRelatorioActionPerformed

    private void RcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RcliActionPerformed
        
       new TelaRelatorioClientePGA().setVisible(true);dispose();
    }//GEN-LAST:event_RcliActionPerformed

    private void BtVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVendasActionPerformed
        
        new telaVendas().setVisible(true);dispose();
    }//GEN-LAST:event_BtVendasActionPerformed

    private void btentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btentradaActionPerformed
        
        new TelaEntradaPGA().setVisible(true);dispose();
    }//GEN-LAST:event_btentradaActionPerformed

    private void RFORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RFORActionPerformed
        
        new TelaRelatorioFornecedorPGA_1().setVisible(true);dispose();
    }//GEN-LAST:event_RFORActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       
        new TelaRelatorioFuncionarioPGA1().setVisible(true);dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        new TelaRelatorioProdutoPGA().setVisible(true);dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioPGA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioPGA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioPGA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorioPGA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorioPGA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtVendas;
    private javax.swing.JButton RFOR;
    private javax.swing.JButton Rcli;
    private javax.swing.JMenuItem btEncerrarSessaoRalatorioMenu;
    private javax.swing.JButton btInicial;
    private javax.swing.JMenuItem btInicialRalatorioMenu;
    private javax.swing.JButton btPrincipalRalatorio;
    private javax.swing.JButton btRelatorioCliente;
    private javax.swing.JButton btRelatorioFornecedor;
    private javax.swing.JButton btRelatorioFuncionario;
    private javax.swing.JButton btRelatorioProduto;
    private javax.swing.JButton btSairRelatorio;
    private javax.swing.JButton btentrada;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
